title: cvless
description: Jekyll theme for a beautiful online CV
baseurl: ""
url: https://SaeedRazavikia.github.io

theme: cvless

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
cv: true

# author settings
author:
  name: Saeed Razavi
  email: sraz@kth.se
photo: assets/files/photo.jpg
address: Teknikringen 33

# profile links
profile:
  Google Scholar: https://scholar.google.com/citations?hl=en&user=8Nh5BBMAAAAJ&view_op=list_works&sortby=pubdate
  linkedin: https://www.linkedin.com/in/saeed-razavi-16a045b2/

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
